#!/usr/bin/env bash

SESSION="GameHQ Plugins"

tmux rename "$SESSION"

# Clean exsting windows
tmux kill-window -a
tmux rename-window bootstrap

# --- Window 1 ---
tmux new-window -n Blueprints -c ~/Documents/Projects/Forge/gamehq-blueprints/
tmux send-keys -t Blueprints 'nvim .' C-m 

# --- Window 2 ---
tmux new-window -n OFA -c ~/Documents/Projects/Forge/ofa-gamehq-plugin/
tmux send-keys -t OFA 'nvim .' C-m 

# --- Window 3 ---
tmux new-window -n Play -c ~/Documents/Projects/Forge/forge-gamehq-plugin/
tmux send-keys -t Play 'nvim .' C-m 

# --- Window 4 ---
tmux new-window -n SuperB -c ~/Documents/Projects/Forge/superb-gamehq-plugin/
tmux send-keys -t SuperB 'nvim .' C-m 

# --- Window 5 ---
tmux new-window -n Storebound -c ~/Documents/Projects/Forge/storebound-gamehq-plugin/
tmux send-keys -t Storebound 'nvim .' C-m 

# --- Window 6 ---
tmux new-window -n NZXT -c ~/Documents/Projects/Forge/nzxt-gamehq-plugin/
tmux send-keys -t NZXT 'nvim .' C-m 

# --- Window 7 ---
tmux new-window -n Xociety -c ~/Documents/Projects/Forge/xociety-gamehq-plugin/
tmux send-keys -t Xociety 'nvim .' C-m 

# Select default window
tmux select-window -t Blueprints

# Remove bootstrap window
tmux kill-window -t bootstrap

