#!/usr/bin/env bash

SESSION="GameHQ Playtester"

tmux rename "$SESSION"

# Clean exsting windows
tmux kill-window -a
tmux rename-window bootstrap

# --- Window 1 ---
tmux new-window -n Blueprints -c ~/Documents/Projects/Forge/hq/gamehq-blueprints/
tmux send-keys -t Blueprints 'nvim .' C-m 
#
# --- Window 3 ---
tmux new-window -n Plugin -c ~/Documents/Projects/Forge/hq/forge-gamehq-plugin/
tmux send-keys -t Plugin 'nvim .' C-m 

# Select default window
tmux select-window -t Playtester

# Remove bootstrap window
tmux kill-window -t bootstrap

