#!/usr/bin/env bash

SESSION="Management"
WORKDIR=~/Documents/Projects/Forge/worklog/

tmux rename "$SESSION"

# Clean exsting windows
tmux kill-window -a
tmux rename-window bootstrap

tmux new-window -n Planning -c "$WORKDIR"
tmux send-keys -t Planning 'claude' C-m 

tmux new-window -n DayPriorities -c "$WORKDIR"
tmux send-keys -t DayPriorities 'nvim ./day.md' C-m 

tmux new-window -n WeekPriorities -c "$WORKDIR"
tmux send-keys -t WeekPriorities 'nvim ./week.md' C-m 

tmux new-window -n OpenThreads -c "$WORKDIR"
tmux send-keys -t OpenThreads 'nvim ./open_threads.md' C-m 

tmux new-window -n Risks -c "$WORKDIR"
tmux send-keys -t Risks 'nvim ./risks.md' C-m 

tmux new-window -n Changelog -c "$WORKDIR"
tmux send-keys -t Changelog 'nvim ./changelog.md' C-m 

# Select default window
tmux select-window -t Planning

# Remove bootstrap window
tmux kill-window -t bootstrap

